[project]
name = "ids-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lewis Parnell", email = "lewis.g.parnell@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
	"capstone-ids"
]

[tool.uv.sources]
capstone-ids = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
